import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Miigii</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h1 className={styles.header}>Miigii</h1>
        <div className={styles.years}>
          <div id="2018">2018</div>
          <div id="2019">2019</div>
          <div id="2020">2020</div>
          <div id="2021">2021</div>
          <div id="2022">2022</div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
