import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Year, Record } from "./types/HomeTypes";

interface HomeProps {
  years: Year[];
}

const Home: NextPage = ({ years }: HomeProps) => {
  years.sort((a, b) => a.fields.Name - b.fields.Name);
  console.log(years);
  return (
    <div className={styles.container}>
      <Head>
        <title>Miigii</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h1 className={styles.header}>Miigii</h1>
        <div className={styles.years}>
          {years.map((year) => {
            return (
              <div
                key={year.id}
                id={year.fields.Name.toString()}
                style={{
                  backgroundImage: `url(${year.fields.Image[0].url})`,
                  backgroundRepeat: "no-repeat",
                  backgroundSize: "cover",
                  backgroundPosition: "center top",
                }}
              >
                <p>{year.fields.Name}</p>
              </div>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;

export async function getStaticProps({}) {
  const url = `https://api.airtable.com/v0/appvWjkNwxwdONFnS/Home\?api_key\=${process.env.DB_KEY}`;
  const response = await fetch(url);
  const record: Record = await response.json();
  return {
    props: { years: record.records },
  };
}
